#version 450

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer ProbeInput {
    uint words[];
} sourceData;

layout(set = 0, binding = 1, std430) writeonly buffer ProbeOutput {
    uint words[];
} drawData;

void main()
{
    const uint index = gl_GlobalInvocationID.x;
    if (index < 32) {
        drawData.words[index] = sourceData.words[index];
    }
}
